#!/usr/bin/env python3
"""Rebuild static/ from the source mockups and inject the demo switcher.

The three mockups are standalone: no links between them and nothing back to the
landing page. Without a switcher a reviewer has to type URLs, which is the fastest
way to make a good prototype feel broken.

The switcher is a fixed pill at the bottom of the viewport. It is injected before
</body>, uses a unique class prefix, and sets no styles on any existing element, so
it cannot disturb the mockup's own layout.

    python3 build.py            rebuild from SOURCES
    python3 build.py --check    verify the switcher is present in every page

Re-running is safe: an existing switcher is stripped before the new one goes in.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
STATIC = ROOT / "static"
DOWNLOADS = Path.home() / "Downloads"

# output name -> source file
SOURCES = {
    "netsuite.html": DOWNLOADS / "pvms-netsuite_1.html",
    "new-application.html": DOWNLOADS / "PMVSfiles" / "pvms-new-application.html",
    "vendor-portal.html": DOWNLOADS / "pvms-vendor-portal.html",
}

# route, label, which output file it is
NAV = [
    ("/new-application", "New Application", "new-application.html"),
    ("/vendor-portal", "Vendor Portal", "vendor-portal.html"),
    ("/netsuite", "NetSuite View", "netsuite.html"),
]

MARK_OPEN = "<!-- pvms-switcher:start -->"
MARK_CLOSE = "<!-- pvms-switcher:end -->"


def switcher(current: str) -> str:
    links = []
    for href, label, page in NAV:
        cls = "pvmsnav__link pvmsnav__link--on" if page == current else "pvmsnav__link"
        aria = ' aria-current="page"' if page == current else ""
        links.append(f'<a class="{cls}" href="{href}"{aria}>{label}</a>')
    return f"""{MARK_OPEN}
<style>
  .pvmsnav{{
    position:fixed; left:50%; bottom:18px; transform:translateX(-50%);
    z-index:2147483000; display:flex; align-items:center; gap:4px;
    padding:5px; border-radius:999px;
    background:rgba(13,31,48,.93); backdrop-filter:blur(8px);
    box-shadow:0 4px 12px rgba(13,31,48,.2), 0 16px 40px rgba(13,31,48,.28);
    font:500 13px/1 "DM Sans",system-ui,-apple-system,Segoe UI,sans-serif;
    max-width:calc(100vw - 24px); overflow:auto; -webkit-overflow-scrolling:touch;
  }}
  .pvmsnav__home{{
    display:flex; align-items:center; gap:6px; flex:0 0 auto;
    color:#9fc4ea; text-decoration:none; padding:8px 12px; border-radius:999px;
    white-space:nowrap;
  }}
  .pvmsnav__home:hover{{color:#fff; background:rgba(255,255,255,.09)}}
  .pvmsnav__sep{{width:1px; height:18px; background:rgba(255,255,255,.18); flex:0 0 auto}}
  .pvmsnav__link{{
    flex:0 0 auto; color:#d5e3f2; text-decoration:none; padding:8px 13px;
    border-radius:999px; white-space:nowrap; transition:background .14s, color .14s;
  }}
  .pvmsnav__link:hover{{color:#fff; background:rgba(255,255,255,.11)}}
  .pvmsnav__link--on{{color:#0d1f30; background:#fff}}
  .pvmsnav__link--on:hover{{color:#0d1f30; background:#fff}}
  @media print{{ .pvmsnav{{display:none}} }}
</style>
<nav class="pvmsnav" aria-label="Prototype pages">
  <a class="pvmsnav__home" href="/" title="All three entry points">&#8962; Overview</a>
  <span class="pvmsnav__sep"></span>
  {chr(10) + '  ' + (chr(10) + '  ').join(links)}
</nav>
{MARK_CLOSE}"""


def strip_existing(html: str) -> str:
    return re.sub(re.escape(MARK_OPEN) + r".*?" + re.escape(MARK_CLOSE), "",
                  html, flags=re.S).rstrip() + "\n"


def build() -> int:
    STATIC.mkdir(exist_ok=True)
    missing = [str(p) for p in SOURCES.values() if not p.is_file()]
    if missing:
        for m in missing:
            print(f"missing source: {m}", file=sys.stderr)
        return 1

    for out_name, src in SOURCES.items():
        html = strip_existing(src.read_text(encoding="utf-8", errors="replace"))
        block = switcher(out_name)
        low = html.lower()
        idx = low.rfind("</body>")
        html = (html[:idx] + block + "\n" + html[idx:]) if idx != -1 else html + block + "\n"
        (STATIC / out_name).write_text(html, encoding="utf-8")
        size = (STATIC / out_name).stat().st_size
        print(f"built static/{out_name:<22} from {src.name}  ({size:,} bytes on disk)")

    if not (STATIC / "index.html").is_file():
        print("warning: static/index.html is missing, the landing page is hand written "
              "and is not generated by this script", file=sys.stderr)
    return 0


def check() -> int:
    bad = 0
    for out_name in SOURCES:
        p = STATIC / out_name
        if not p.is_file():
            print(f"FAIL {out_name}: not built")
            bad += 1
            continue
        html = p.read_text(encoding="utf-8")
        if MARK_OPEN not in html:
            print(f"FAIL {out_name}: switcher missing")
            bad += 1
            continue
        hrefs = {h for _, _, _ in NAV for h in [_]} if False else {n[0] for n in NAV}
        missing = [h for h in hrefs | {"/"} if f'href="{h}"' not in html]
        if missing:
            print(f"FAIL {out_name}: switcher missing links {missing}")
            bad += 1
        else:
            print(f"ok   {out_name}: switcher present, 4 links")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(check() if "--check" in sys.argv else build())
